logging.level.root=${LOG_LEVEL:ERROR}
logging.file.name=${LOG_FILE_NAME:${user.home}/Desktop/logs/app-prod.log}
spring.jpa.show-sql=${JPA_SHOW_URL:false}
spring.jpa.properties.hibernate.format_sql=${HIBERNATE_FORMAT_SQL:false}
contact.phone=+821084628952
contact.email=prod.bayramyaxiyaev7@gmail.com
contact.address=Itaewon street, Seul City, S.Korea
